### ISSUE TITLE
How does this compare to redux-ui?

### ISSUE THREAD

**Issue by pke** [ashaffer/redux-ephemeral#3]
From outside they both seem to do the same. I need to add a library that handles transient UI state and [`redux-ui`](https://github.com/tonyhb/redux-ui) seems to do more heavy lifting. But it also seems to support persisting _some_ properties which is neat if we want preserve some ui state between pages.

**Comment by ashaffer** [comment]
I'd say the main differences are that redux-ephemeral:
- is not opinionated about your UI renderer, whereas redux-ui is coupled to React.
- uses an HAMT internally by default so that state updates are fast
- lets you use actions/reducers inside of your components themselves

**Comment by pke** [comment]
I'll give it a try. Immutable of redux-ui breaks my simple persistence layer.
